-- MySQL Script generated by MySQL Workbench
-- Fri Mar 31 12:33:39 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema library
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `library` ;

-- -----------------------------------------------------
-- Schema library
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `library` DEFAULT CHARACTER SET utf8 ;
USE `library` ;

-- -----------------------------------------------------
-- Table `library`.`table1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `library`.`table1` ;

CREATE TABLE IF NOT EXISTS `library`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`Member`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `library`.`Member` ;

CREATE TABLE IF NOT EXISTS `library`.`Member` (
  `Member_id` INT NOT NULL AUTO_INCREMENT,
  `Last_name` VARCHAR(45) NOT NULL,
  `First_name` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(80) NOT NULL,
  `Status_ID` INT NOT NULL,
  `CPR` BIGINT(10) NOT NULL,
  `Photograph` VARCHAR(150) NULL,
  PRIMARY KEY (`Member_id`),
  UNIQUE INDEX `Member_id_UNIQUE` (`Member_id` ASC),
  UNIQUE INDEX `CPR_UNIQUE` (`CPR` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
